# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankleitzahl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankleitzahl', models.CharField(max_length=8)),
                ('zahlungsdienstleister', models.CharField(choices=[(b'1', b'Ja'), (b'2', b'Nein')], default=b'2', help_text=b'Merkmal, ob bankleitzahlfu\xcc\x88hrender Zahlungsdienstleister (\xe2\x80\x9e1\xe2\x80\x9c) oder nicht (\xe2\x80\x9e2\xe2\x80\x9c)', max_length=1)),
                ('bezeichnung', models.CharField(help_text=b'Bezeichnung des Zahlungsdienstleisters (ohne Rechtsform)', max_length=58)),
                ('postleitzahl', models.CharField(max_length=5)),
                ('ort', models.CharField(max_length=35)),
                ('kurzbezeichnung', models.CharField(help_text=b'Kurzbezeichnung des Zahlungsdienstleisters mit Ort (ohne Rechtsform)', max_length=27)),
                ('pan', models.CharField(help_text=b'Institutsnummer f\xc3\xbcr PAN', max_length=5)),
                ('bic', models.CharField(help_text=b'Business Identifier Code', max_length=11)),
                ('pruefzifferberechnungsmethode', models.CharField(help_text=b'Kennzeichen f\xc3\xbcr Pr\xc3\xbcfzifferberechnungsmethode', max_length=2, verbose_name=b'Berechnungsmethode')),
                ('datensatz', models.CharField(help_text=b'Nummer des Datensatzes', max_length=6)),
                ('indikator_geaendert', models.CharField(choices=[(b'A', b'Neu'), (b'D', b'Gel\xc3\xb6scht'), (b'M', b'Ver\xc3\xa4ndert'), (b'U', b'Unver\xc3\xa4ndert')], default=b'A', help_text=b'\xc3\x84nderungskennzeichen \xe2\x80\x9eA\xe2\x80\x9c (Addition) f\xc3\xbcr neue, \xe2\x80\x9eD\xe2\x80\x9c (Deletion) f\xc3\xbcr gel\xc3\xb6schte, \xe2\x80\x9eU\xe2\x80\x9c(Unchanged) f\xc3\xbcr unver\xc3\xa4nderte und \xe2\x80\x9eM\xe2\x80\x9c (Modified) f\xc3\xbcr ver\xc3\xa4nderte Datens\xc3\xa4tze', max_length=1)),
                ('indikator_loeschung', models.CharField(choices=[(b'0', b'Keine Angabe'), (b'1', b'Zur L\xc3\xb6schung vorgesehen')], default=b'0', help_text=b'Hinweis auf eine beabsichtigte Bankleitzahll\xc3\xb6schung', max_length=1)),
                ('nachfolge_bankleitzahl', models.CharField(help_text=b'Hinweis auf Nachfolge-Bankleitzahl', max_length=8)),
                ('iban_regel', models.CharField(help_text=b'Kennzeichen f\xc3\xbcr die IBAN-Regel', max_length=6)),
            ],
            options={
                'ordering': ('bankleitzahl',),
                'verbose_name': 'Bankleitzahl',
                'verbose_name_plural': 'Bankleitzahlen',
            },
        ),
    ]
